### ISSUE TITLE
NPE in generated property section

### ISSUE THREAD

**Issue by cp-api** [cp-api/test#12]
In some circumstances resolved object is null.

java.lang.NullPointerException
	at org.polarsys.capella.vp.test2.test2.provider.sections.MyLogicalComponent2Section.select(MyLogicalComponent2Section.java:22)
	at org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyRegistryClassSectionFilter.appliesToSelection(TabbedPropertyRegistryClassSectionFilter.java:82)
	at org.eclipse.ui.views.properties.tabbed.AbstractSectionDescriptor.appliesTo(AbstractSectionDescriptor.java:57)
	at org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyRegistry.adaptDescriptorFor(TabbedPropertyRegistry.java:328)
	at org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyRegistry.filterTabDescriptors(TabbedPropertyRegistry.java:305)
	at org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyRegistry.getTabDescriptors(TabbedPropertyRegistry.java:291)
	at org.polarsys.capella.common.flexibility.wizards.ui.tabbed.FixedTabDescriptorProvider.getTabDescriptors(FixedTabDescriptorProvider.java:75)
	at org.eclipse.ui.internal.views.properties.tabbed.view.TabbedPropertyRegistry.getTabDescriptors(TabbedPropertyRegistry.java:287)
	at org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage.setInput(TabbedPropertySheetPage.java:718)
	at org.eclipse.ui.views.properties.tabbed.TabbedPropertySheetPage.selectionChanged(TabbedPropertySheetPage.java:555)
	at org.eclipse.ui.views.properties.PropertySheet.selectionChanged(PropertySheet.java:365)
	at org.eclipse.ui.internal.AbstractSelectionService.firePostSelection(AbstractSelectionService.java:179)
	at org.eclipse.ui.internal.AbstractSelectionService$2.selectionChanged(AbstractSelectionService.java:71)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:888)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:49)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:175)

`🆔 ECLIPSE-553918 / POLARSYS-263` `👷 thomas.guiu` `📅 2015-03-25` `🔎 0.8.2`

**Comment by cp-api** [comment]
**thomas.guiu** commented on 2015-03-25
> *** [POLARSYS-247](https://github.com/search?q=POLARSYS-247&type=Issues) has been marked as a duplicate of this bug. ***

**ci-bot** commented on 2015-06-23
> Merged to [v0.8.x].
 > Commit: [84cb7b577a5b51568f9e83e744600ef34d56bf2a](https://github.com/search?q=84cb7b577a5b51568f9e83e744600ef34d56bf2a&type=Commits)

**ci-bot** commented on 2015-06-23
> Merged to [master].
 > Commit: [6b20c541a66887434fb7bca78a74850843efee3a](https://github.com/search?q=6b20c541a66887434fb7bca78a74850843efee3a&type=Commits)

**thomas.guiu** commented on 2015-09-21
> fixed
