### ISSUE TITLE
Clean Session lead to exceptions

### ISSUE THREAD

**Issue by cp-api** [cp-api/test#3]
!ENTRY org.eclipse.sirius 4 0 2018-02-28 15:48:40.089
!MESSAGE the program was not able close the session
!STACK 0
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:476)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:500)
	at org.polarsys.capella.core.sirius.ui.actions.CloseSessionAction.run(CloseSessionAction.java:108)
	at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:170)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:116)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
Caused by: org.eclipse.emf.cdo.common.util.CDOException: Attempt to remove a dirty resource from a resource set: CDOResource@OID5[DIRTY]("cdo://repoTESTONE/XXX/XXX.aird")
	at org.eclipse.emf.internal.cdo.view.CDOViewSetImpl.deregisterResources(CDOViewSetImpl.java:363)
	at org.eclipse.emf.internal.cdo.view.CDOViewSetImpl.notifyChanged(CDOViewSetImpl.java:320)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.emf.common.notify.impl.NotificationChainImpl.dispatch(NotificationChainImpl.java:98)
	at org.eclipse.emf.common.notify.impl.NotificationChainImpl.dispatch(NotificationChainImpl.java:86)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.remove(NotifyingListImpl.java:718)
	at org.eclipse.emf.common.util.AbstractEList.remove(AbstractEList.java:462)
	at org.polarsys.capella.core.sirius.ui.closeproject.SessionCloseManager.cleanSession(SessionCloseManager.java:210)
	at org.polarsys.capella.core.sirius.ui.actions.CloseSessionAction$CloseSessionCommand.closeSession(CloseSessionAction.java:244)
	at org.polarsys.capella.core.sirius.ui.actions.CloseSessionAction$CloseSessionCommand.run(CloseSessionAction.java:274)
	at org.polarsys.capella.core.sirius.ui.actions.CloseSessionAction$CloseSessionOperation.run(CloseSessionAction.java:177)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
	... 34 more
Root exception:
org.eclipse.emf.cdo.common.util.CDOException: Attempt to remove a dirty resource from a resource set: CDOResource@OID5[DIRTY]("cdo://repoTESTONE/XXX/XXX.aird")
	at org.eclipse.emf.internal.cdo.view.CDOViewSetImpl.deregisterResources(CDOViewSetImpl.java:363)
	at org.eclipse.emf.internal.cdo.view.CDOViewSetImpl.notifyChanged(CDOViewSetImpl.java:320)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.emf.common.notify.impl.NotificationChainImpl.dispatch(NotificationChainImpl.java:98)
	at org.eclipse.emf.common.notify.impl.NotificationChainImpl.dispatch(NotificationChainImpl.java:86)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.remove(NotifyingListImpl.java:718)
	at org.eclipse.emf.common.util.AbstractEList.remove(AbstractEList.java:462)
	at org.polarsys.capella.core.sirius.ui.closeproject.SessionCloseManager.cleanSession(SessionCloseManager.java:210)
	at org.polarsys.capella.core.sirius.ui.actions.CloseSessionAction$CloseSessionCommand.closeSession(CloseSessionAction.java:244)
	at org.polarsys.capella.core.sirius.ui.actions.CloseSessionAction$CloseSessionCommand.run(CloseSessionAction.java:274)
	at org.polarsys.capella.core.sirius.ui.actions.CloseSessionAction$CloseSessionOperation.run(CloseSessionAction.java:177)
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:500)
	at org.polarsys.capella.core.sirius.ui.actions.CloseSessionAction.run(CloseSessionAction.java:108)
	at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:170)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.polarsys.capella.core.platform.sirius.ui.app.CapellaApplication.start(CapellaApplication.java:116)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
!SESSION 2018-02-28 15:49:24.321 ------------------------------------

`🆔 ECLIPSE-553909 / POLARSYS-1976` `👷 philippe.dul` `📅 2018-03-02` `🔎 1.1.4`

**Comment by cp-api** [comment]
**ci-bot** commented on 2018-03-05
> Merged to [v1.1.x].
 > Commit: [e58cda7dd88c5015baf0f39deb67bd7b9e8d2789](https://github.com/search?q=e58cda7dd88c5015baf0f39deb67bd7b9e8d2789&type=Commits)

**ci-bot** commented on 2018-03-12
> Merged to [v1.2.x].
 > Commit: [e916c6955c05c614260f85d57b17cb1be824a6f1](https://github.com/search?q=e916c6955c05c614260f85d57b17cb1be824a6f1&type=Commits)

**ci-bot** commented on 2018-03-13
> Merged to [master].
 > Commit: [4cc9d69aa1a102592d6d08516e1279ca91726e8a](https://github.com/search?q=4cc9d69aa1a102592d6d08516e1279ca91726e8a&type=Commits)

**philippe.dul** commented on 2018-05-18
> fixed

**philippe.dul** commented on 2018-05-23
> Status: verified
 > Resolution: fixed
